# docker-compose.yml
version: '3.7' # Specify version of Docker Compose

services:
  web:
    build: .
    # build the current directory, execute runserver on startup
    command: python /code/manage.py migrate
    command: python /code/manage.py runserver 0.0.0.0:8000 
    volumes:
      - .:/code
    ports:
      # expose port 8000 which is Django’s default so the container will expose it, too.
      - 8000:8000