# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3

      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: libdb
          POSTGRES_DB: libdb
          POSTGRES_PASSWORD: libdb

    environment:
      - ANSIBLE_HOST_KEY_CHECKING: False
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            pip install --upgrade setuptools
            sudo apt-get install python3-venv
            python3 -m venv myenv
            . myenv/bin/activate
            pip install tox
            
      # Step 3: run linter and tests (will all be run by tox command)
      - run:
          name: run tests
          command: |          
            # Run tox
            . myenv/bin/activate
            # Whenever we change the project dependencies we have to tell tox to recreate our environments 
            tox --recreate # Force tox to recreate the venv
            
        