---

- name: Deploy to server
  hosts: all
  vars_files:
    - vars.yml
  become: yes

  tasks:
    - name: Install System Packages
      apt: name={{ system_packages }} update-cache=yes

    - name: Copy .env file
      copy:
        src: /home/kevin/Documents/LibraryApp/LibAppDjango/.env
        dest: /home/kevin/LibAppServ/

    - name: Create Database
      become_user: postgres
      postgresql_db: name={{ POSTGRES_DB }}

    - name: Create Database user
      become_user: postgres
      postgresql_user: db={{ POSTGRES_DB }} name={{ POSTGRES_USER }} password={{ POSTGRES_PASSWORD }}

    - name: Install virtualenv
      pip: name=virtualenv executable=pip3
      
    - name: Deploy from pip registry to virtualenv
      pip: 
        name: LibraryApp==1.2.7
        virtualenv: /home/kevin/LibAppServ/myenv
    
    - name: Pip install gunicorn
      pip: name=gunicorn virtualenv=/home/kevin/LibAppServ/myenv

    - name: Perform migration
      shell:
        cd LibAppServ
        . myenv/bin/activate
        docs_app migrate

    - name: Copy nginx conf file
      copy:
        src: /home/kevin/Documents/LibraryApp/LibAppDjango/confdns
        dest: /etc/nginx/sites-available

    - name: Create Symbolic link
      file:
        src: /etc/nginx/sites-available/confdns
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: start gunicorn
      shell: |
        cd LibAppServ
        . myenv/bin/activate
        gunicorn --daemon --workers 3 --bind unix:/home/kevin/LibAppServ/LibAppServ.sock locallibrary.wsgi

    - name: Allow UFW
      ufw:
        state: enabled

    - name: Allow OpenSSH
      ufw:
        rule: allow
        name: OpenSSH

    - name: Allow Nginx Full
      ufw:
        rule: allow
        name: Nginx Full

    - name: Restart nginx to make changes
      service:
        name: nginx
        state: restarted